common: 
    model: imgonly
    resume: ./runs/Mar04_21-11-53_dp3090sti_imageonly_allsketch/best_checkpoint.pth

    logger_comment: sti_imageonly_allsketch
    logger_path: ./runs/
    best_model: True
    model_path: ./runs/

    dataset: 
        type: Full
        name: STI
        dataset_path: ./STI
        loader_num_workers: 4
        shuffle: True
        drop_last: True


    num_epochs: 10000
    num_iters: 160000
    batch_size: 64

    loss: soft_triplet
    embed_dim: 512

    img_model: resnet18

    lr_scheduler:
        type: ReduceLROnPlateau      
        learning_rate_decay_frequency: 500
        learning_rate_factor: 0.5
    
    optimizer: 
        type: SGD
        learning_rate: 0.01
        momentum: 0.9
        weight_decay: 0.00005
