common: 
    model: imgonly
    resume: False

    logger_comment: sti_imageonly_allsketch
    logger_path: /data/zzm/tmp/logs/stiretrival/
    best_model: True
    model_path: /data/zzm/tmp/logs/stiretrival/

    dataset: 
        type: Full
        name: STI
        dataset_path: /data/zzm/datasets/STI
        loader_num_workers: 4
        shuffle: True
        drop_last: True


    num_epochs: 10000
    num_iters: 160000
    batch_size: 64

    loss: soft_triplet
    embed_dim: 512

    img_model: resnet18

    lr_scheduler:
        type: ReduceLROnPlateau      
        learning_rate_decay_frequency: 500
        learning_rate_factor: 0.5
    
    optimizer: 
        type: SGD
        learning_rate: 0.01
        momentum: 0.9
        weight_decay: 0.00005
